services:
  sqlPlaybookMariaDb:
    image: mariadb
    restart: always
    container_name: sqlPlaybookMariaDb
    ports:
      - "3306:3306"
    volumes:
      - .:/code
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_DATABASE=web
